name: My first workflow

on: push

jobs:
    first_job:
      runs-on: ubuntu-latest

      steps:
      - name: Welcome message
        run: echo "My First Github Actions Job"

      - name: List files
        run: ls -al

      - name: Readfile
        run: cat README.md